spring.application.name=springai-intro

spring.at.model.chat=ollama
spring.ai.ollama.chat.options.model=llama3.2:3b

sfg.aiapp.vectorStorePath=C:/Users/rituj/AppData/Local/Temp/vectorstore.json
sfg.aiapp.documentsToLoad[0]=classpath:/movies500.csv